# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62918241db4559c2252bf00808fa959fdd80d6e6707f34288c3797468af81f967b9e06c8db16400c7606ecb3335ecfbbe82354cabdf255efb5ae6fe91f653083

test:
  secret_key_base: 2d49704553c8b8aa03fd0141f09d172188fd3619612a7c40d52e1d17692dc791edba89777e57317f554e230b188f78f0e2d4832a21fe29baf1da03102e993787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
